<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AvaloniaVersion>12.0.4</AvaloniaVersion>
    <SemiAvaloniaVersion>12.0.3</SemiAvaloniaVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="AnimatedImage.Avalonia" Version="2.1.4" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Lang.Avalonia.Json" Version="12.0.3.3" />
    <PackageVersion Include="Markdig" Version="1.2.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageVersion Include="Semi.Avalonia" Version="$(SemiAvaloniaVersion)" />
    <PackageVersion Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageVersion Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.11" />
    <PackageVersion Include="Svg.Skia" Version="5.0.0" />
    <PackageVersion Include="Sylinko.CSharpMath.Avalonia" Version="12.0.0" />
    <PackageVersion Include="TextMateSharp" Version="2.0.3" />
    <PackageVersion Include="TextMateSharp.Grammars" Version="2.0.3" />
    <PackageVersion Include="VC-LTL" Version="5.3.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="YY-Thunks" Version="1.2.2-Beta.2" />
  </ItemGroup>
</Project>